# Patch only the build-local auth plugin. Android and pub-cache stay unchanged.
function(gkii_guard_signed_out_auth)
  get_target_property(sources firebase_auth_plugin SOURCES)
  get_target_property(source_dir firebase_auth_plugin SOURCE_DIR)
  find_package(Python3 REQUIRED COMPONENTS Interpreter)
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/../tool/patch_windows_auth.py")
  set(patched_sources "")
  set(found 0)
  foreach(source IN LISTS sources)
    if(IS_ABSOLUTE "${source}")
      set(original "${source}")
    else()
      set(original "${source_dir}/${source}")
    endif()
    if(source MATCHES "(^|/)firebase_auth_plugin\\.cpp$")
      set(patched "${CMAKE_BINARY_DIR}/gkii-auth/firebase_auth_plugin.cpp")
      set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${original}")
      execute_process(COMMAND "${Python3_EXECUTABLE}"
        "${CMAKE_CURRENT_SOURCE_DIR}/../tool/patch_windows_auth.py"
        "${original}" "${patched}" RESULT_VARIABLE status)
      if(NOT status EQUAL 0)
        message(FATAL_ERROR "Windows auth listener changed; review signed-out guard")
      endif()
      list(APPEND patched_sources "${patched}")
      math(EXPR found "${found} + 1")
    else()
      list(APPEND patched_sources "${original}")
    endif()
  endforeach()
  if(NOT found EQUAL 1)
    message(FATAL_ERROR "Windows auth listener source missing")
  endif()
  set_target_properties(firebase_auth_plugin PROPERTIES SOURCES "${patched_sources}")
  target_include_directories(firebase_auth_plugin PRIVATE "${source_dir}")
endfunction()
