# Patch a build-local copy, preserving the installed FlutterFire package.
function(gkii_guard_firestore_settings)
  get_target_property(sources cloud_firestore_plugin SOURCES)
  get_target_property(source_dir cloud_firestore_plugin SOURCE_DIR)
  set(found FALSE)
  set(patched_sources "")
  foreach(source IN LISTS sources)
    if(source MATCHES "(^|/)cloud_firestore_plugin\\.cpp$")
      if(IS_ABSOLUTE "${source}")
        set(original "${source}")
      else()
        set(original "${source_dir}/${source}")
      endif()
      set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${original}")
      file(READ "${original}" contents)
      string(REGEX MATCHALL "firestore->set_settings\\(settings\\)" assignments "${contents}")
      list(LENGTH assignments count)
      if(NOT count EQUAL 1)
        message(FATAL_ERROR "FlutterFire Windows settings implementation changed; review guard")
      endif()
      string(REPLACE "firestore->set_settings(settings);"
        "gkii_apply_firestore_settings(firestore, settings);" contents "${contents}")
      set(patched "${CMAKE_BINARY_DIR}/gkii-firestore/cloud_firestore_plugin.cpp")
      file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/gkii-firestore")
      file(WRITE "${patched}" "#include \"firestore_settings_guard.h\"\n${contents}")
      list(APPEND patched_sources "${patched}")
      set(found TRUE)
    else()
      # Preserve relative plugin paths when assigning SOURCES from our directory.
      if(IS_ABSOLUTE "${source}" OR source MATCHES "^\\$<")
        list(APPEND patched_sources "${source}")
      else()
        list(APPEND patched_sources "${source_dir}/${source}")
      endif()
    endif()
  endforeach()
  if(NOT found)
    message(FATAL_ERROR "FlutterFire Windows source not found")
  endif()
  set_target_properties(cloud_firestore_plugin PROPERTIES SOURCES "${patched_sources}")
  target_include_directories(cloud_firestore_plugin PRIVATE
    "${source_dir}" "${CMAKE_CURRENT_SOURCE_DIR}")

  add_executable(gkii_firestore_settings_test "../test/native/firestore_settings_test.cpp")
  target_include_directories(gkii_firestore_settings_test PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}")
  target_link_libraries(gkii_firestore_settings_test PRIVATE firebase_app firebase_auth firebase_firestore snappy
    advapi32 ws2_32 crypt32 rpcrt4 ole32 icu shell32 bcrypt dbghelp)
  set_target_properties(gkii_firestore_settings_test PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/native-tests")
  add_dependencies(${BINARY_NAME} gkii_firestore_settings_test)
endfunction()
