function(gkii_fix_storage_lifetime)
  find_package(Python3 REQUIRED COMPONENTS Interpreter)
  get_target_property(sources firebase_storage_plugin SOURCES)
  get_target_property(source_dir firebase_storage_plugin SOURCE_DIR)
  set(patched_sources "")
  set(found FALSE)
  foreach(source IN LISTS sources)
    if(source MATCHES "(^|/)firebase_storage_plugin\\.cpp$")
      if(IS_ABSOLUTE "${source}")
        set(original "${source}")
      else()
        set(original "${source_dir}/${source}")
      endif()
      set(patcher "${CMAKE_CURRENT_SOURCE_DIR}/../tool/patch_windows_storage.py")
      set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${original}" "${patcher}")
      set(patched "${CMAKE_BINARY_DIR}/gkii-storage/firebase_storage_plugin.cpp")
      execute_process(COMMAND "${Python3_EXECUTABLE}" "${patcher}"
        --input "${original}" --output "${patched}"
        RESULT_VARIABLE status ERROR_VARIABLE errors)
      if(NOT status EQUAL 0)
        message(FATAL_ERROR "Storage lifetime patch failed: ${errors}")
      endif()
      list(APPEND patched_sources "${patched}")
      set(found TRUE)
    elseif(IS_ABSOLUTE "${source}" OR source MATCHES "^\\$<")
      list(APPEND patched_sources "${source}")
    else()
      list(APPEND patched_sources "${source_dir}/${source}")
    endif()
  endforeach()
  if(NOT found)
    message(FATAL_ERROR "Firebase Storage Windows source not found")
  endif()
  set_target_properties(firebase_storage_plugin PROPERTIES SOURCES "${patched_sources}")
  target_include_directories(firebase_storage_plugin PRIVATE "${source_dir}" "${CMAKE_CURRENT_SOURCE_DIR}")
  add_executable(gkii_storage_lifetime_test "../test/native/storage_lifetime_test.cpp")
  target_compile_features(gkii_storage_lifetime_test PRIVATE cxx_std_17)
  target_include_directories(gkii_storage_lifetime_test PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}")
  set_target_properties(gkii_storage_lifetime_test PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/native-tests")
  add_dependencies(${BINARY_NAME} gkii_storage_lifetime_test)
endfunction()
