name: gereja_mobile
description: "Aplikasi Gereja GKII Siloam V2 - Flutter Version"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # --- UI & UTILITAS ---
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  fl_chart: ^0.70.0
  shimmer: ^3.0.0
  shared_preferences: ^2.3.5
  permission_handler: ^11.3.1
  share_plus: ^10.1.0

  # --- NETWORK & API ---
  http: ^1.2.0
  html: ^0.15.4
  google_generative_ai: ^0.4.7

  # --- MEDIA & FILE HANDLING (Chatroom) ---
  image_picker: ^1.1.2
  file_picker: ^8.0.1
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  open_filex: ^4.4.0      # 👈 WAJIB: Untuk buka file PDF/Word/WPS
  audioplayers: ^5.2.1    # 👈 WAJIB: Untuk fitur Voice Note
  record: ^5.1.2

  # --- FIREBASE & ONESIGNAL ---
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.10
  google_sign_in: ^6.2.1
  onesignal_flutter: ^5.2.6

  # --- DATABASE LOKAL (Alkitab) ---
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # --- PENDAFTARAN ASSETS ---
  assets:
    - assets/TB.SQLite3
    - assets/TJL.SQLite3
    # - assets/images/

# 👇 INI KUNCI SAKTINYA BOS 👇
dependency_overrides:
  record_platform_interface: 1.4.0
  record_linux: 0.7.2