import 'dart:math';

class AyatData {
  static final List<Map<String, String>> daftarAyat = [
    {"ref": "Mazmur 23:1", "isi": "TUHAN adalah gembalaku, takkan kekurangan aku."},
    {"ref": "Yesaya 41:10", "isi": "Janganlah takut, sebab Aku menyertai engkau, janganlah bimbang, sebab Aku ini Allahmu."},
    {"ref": "Filipi 4:13", "isi": "Segala perkara dapat kutanggung di dalam Dia yang memberi kekuatan kepadaku."},
    {"ref": "Yosua 1:9", "isi": "Kuatkan dan teguhkanlah hatimu! Janganlah kecut dan tawar hati, sebab TUHAN menyertai engkau."},
    {"ref": "Mazmur 46:2", "isi": "Allah itu bagi kita tempat perlindungan dan kekuatan, sebagai penolong dalam kesesakan."},
    {"ref": "Nahum 1:7", "isi": "TUHAN itu baik; Ia adalah tempat pengungsian pada waktu kesusahan."},
    {"ref": "Yesaya 40:31", "isi": "Orang yang menanti-nantikan TUHAN mendapat kekuatan baru: seumpama rajawali yang terbang."},
    {"ref": "2 Timotius 1:7", "isi": "Sebab Allah memberikan bukan roh ketakutan, melainkan roh kekuatan, kasih dan ketertiban."},
    {"ref": "Mazmur 27:1", "isi": "TUHAN adalah terangku dan keselamatanku, kepada siapakah aku harus takut?"},
    {"ref": "Amsal 18:10", "isi": "Nama TUHAN adalah menara yang kuat, ke sanalah orang benar lari dan ia menjadi aman."},
    {"ref": "Mazmur 91:1", "isi": "Orang yang duduk dalam lindungan Yang Mahatinggi akan bermalam dalam naungan Yang Mahakuasa."},
    {"ref": "Keluaran 14:14", "isi": "TUHAN akan berperang untuk kamu, dan kamu akan diam saja."},
    {"ref": "Mazmur 121:2", "isi": "Pertolonganku ialah dari TUHAN, yang menjadikan langit dan bumi."},
    {"ref": "Zefanya 3:17", "isi": "TUHAN Allahmu ada di antaramu sebagai pahlawan yang memberi kemenangan."},
    {"ref": "2 Tesalonika 3:3", "isi": "Tetapi Tuhan adalah setia. Ia akan menguatkan hatimu dan memelihara kamu terhadap yang jahat."},
    {"ref": "Yohanes 3:16", "isi": "Karena begitu besar kasih Allah akan dunia ini, sehingga Ia mengaruniakan Anak-Nya yang tunggal."},
    {"ref": "1 Yohanes 4:19", "isi": "Kita mengasihi, karena Allah lebih dahulu mengasihi kita."},
    {"ref": "Roma 5:8", "isi": "Akan tetapi Allah menunjukkan kasih-Nya kepada kita, oleh karena Kristus telah mati untuk kita."},
    {"ref": "Efesus 4:32", "isi": "Hendaklah kamu ramah, penuh kasih mesra dan saling mengampuni."},
    {"ref": "1 Korintus 16:14", "isi": "Lakukanlah segala pekerjaanmu dalam kasih!"},
    {"ref": "1 Yohanes 1:9", "isi": "Jika kita mengaku dosa kita, maka Ia adalah setia dan adil, sehingga Ia mengampuni segala dosa kita."},
    {"ref": "Mazmur 103:8", "isi": "TUHAN adalah penyayang dan pengasih, panjang sabar dan berlimpah kasih setia."},
    {"ref": "Yeremia 31:3", "isi": "Aku mengasihi engkau dengan kasih yang kekal, sebab itu Aku melanjutkan kasih setia-Ku kepadamu."},
    {"ref": "Yohanes 15:13", "isi": "Tidak ada kasih yang lebih besar dari pada kasih seorang yang memberikan nyawanya untuk sahabatnya."},
    {"ref": "1 Petrus 4:8", "isi": "Sebab kasih menutupi banyak sekali dosa."},
    {"ref": "Yeremia 29:11", "isi": "Sebab Aku tahu rancangan-rancangan apa yang ada pada-Ku, yaitu rancangan damai sejahtera."},
    {"ref": "Matius 6:33", "isi": "Tetapi carilah dahulu Kerajaan Allah, maka semuanya itu akan ditambahkan kepadamu."},
    {"ref": "Amsal 16:3", "isi": "Serahkanlah perbuatanmu kepada TUHAN, maka terlaksanalah segala rencanamu."},
    {"ref": "Malakhi 3:10", "isi": "Bawalah seluruh persembahan persepuluhan, supaya ada persediaan makanan di rumah-Ku."},
    {"ref": "Ulangan 28:2", "isi": "Segala berkat ini akan datang kepadamu dan menjadi bagianmu, asal engkau mendengarkan suara TUHAN."},
    {"ref": "Mazmur 37:4", "isi": "Bergembiralah karena TUHAN; maka Ia akan memberikan kepadamu apa yang diinginkan hatimu."},
    {"ref": "Filipi 4:19", "isi": "Allahku akan memenuhi segala keperluanmu menurut kekayaan dan kemuliaan-Nya dalam Kristus Yesus."},
    {"ref": "Amsal 10:22", "isi": "Berkat TUHANlah yang menjadikan kaya, susah payah tidak akan menambahinya."},
    {"ref": "Bilangan 6:24", "isi": "TUHAN memberkati engkau dan melindungi engkau."},
    {"ref": "Mazmur 1:3", "isi": "Ia seumpama pohon, yang ditanam di tepi aliran air, yang menghasilkan buahnya pada musimnya."},
    {"ref": "Ibrani 11:1", "isi": "Iman adalah dasar dari segala sesuatu yang kita harapkan dan bukti dari yang tidak kita lihat."},
    {"ref": "Markus 11:24", "isi": "Apa saja yang kamu minta dan doakan, percayalah bahwa kamu telah menerimanya."},
    {"ref": "Lukas 1:37", "isi": "Sebab bagi Allah tidak ada yang mustahil."},
    {"ref": "Matius 7:7", "isi": "Mintalah, maka akan diberikan kepadamu; carilah, maka kamu akan mendapat."},
    {"ref": "Yakobus 1:5", "isi": "Apabila di antara kamu ada yang kekurangan hikmat, hendaklah ia memintakannya kepada Allah."},
    {"ref": "Ibrani 4:16", "isi": "Marilah kita dengan penuh keberanian menghampiri takhta kasih karunia."},
    {"ref": "Roma 10:17", "isi": "Jadi, iman timbul dari pendengaran, dan pendengaran oleh firman Kristus."},
    {"ref": "1 Petrus 5:7", "isi": "Serahkanlah segala kekuatiranmu kepada-Nya, sebab Ia yang memelihara kamu."},
    {"ref": "Mazmur 34:18", "isi": "Apabila orang-orang benar itu berseru-seru, maka TUHAN mendengar."},
    {"ref": "Yeremia 33:3", "isi": "Berserulah kepada-Ku, maka Aku akan menjawab engkau."},
    {"ref": "Mazmur 119:105", "isi": "Firman-Mu itu pelita bagi kakiku dan terang bagi jalanku."},
    {"ref": "Amsal 4:23", "isi": "Jagalah hatimu dengan segala kewaspadaan, karena dari situlah terpancar kehidupan."},
    {"ref": "Pengkhotbah 3:11", "isi": "Ia membuat segala sesuatu indah pada waktunya."},
    {"ref": "Kolose 3:23", "isi": "Apapun juga yang kamu perbuat, perbuatlah dengan segenap hatimu seperti untuk Tuhan."},
    {"ref": "1 Tesalonika 5:18", "isi": "Mengucap syukurlah dalam segala hal, sebab itulah yang dikehendaki Allah."},
    {"ref": "Matius 5:16", "isi": "Demikianlah hendaknya terangmu bercahaya, supaya mereka melihat perbuatanmu yang baik."},
    {"ref": "Galatia 5:22", "isi": "Tetapi buah Roh ialah: kasih, sukacita, damai sejahtera, kesabaran, kemurahan, kebaikan, kesetiaan."},
    {"ref": "Roma 12:21", "isi": "Janganlah kamu kalah terhadap kejahatan, tetapi kalahkanlah kejahatan dengan kebaikan!"},
    {"ref": "Mazmur 118:24", "isi": "Inilah hari yang dijadikan TUHAN, marilah kita bersorak-sorak dan bersukacita."},
    {"ref": "Amsal 17:17", "isi": "Seorang sahabat menaruh kasih setiap waktu, dan menjadi seorang saudara dalam kesukaran."},
    {"ref": "Yohanes 14:6", "isi": "Akulah jalan dan kebenaran dan hidup. Tidak ada seorangpun yang datang kepada Bapa, kalau tidak melalui Aku."},
    {"ref": "Lukas 6:31", "isi": "Dan sebagaimana kamu kehendaki supaya orang perbuat kepadamu, perbuatlah juga demikian kepada mereka."},
    {"ref": "Yakobus 4:7", "isi": "Karena itu tunduklah kepada Allah, dan lawanlah Iblis, maka ia akan lari dari padamu!"},
    {"ref": "Roma 12:12", "isi": "Bersukacitalah dalam pengharapan, sabarlah dalam kesesakan, dan bertekunlah dalam doa!"},
    {"ref": "1 Korintus 10:13", "isi": "Pencobaan yang kamu alami ialah pencobaan biasa, yang tidak melebihi kekuatan manusia."},
    {"ref": "Yosua 24:15", "isi": "Tetapi aku dan seisi rumahku, kami akan beribadah kepada TUHAN!"},
    {"ref": "Mazmur 34:8", "isi": "Kecaplah dan lihatlah, betapa baiknya TUHAN itu!"},
    {"ref": "Efesus 2:8", "isi": "Sebab karena kasih karunia kamu diselamatkan oleh iman."},
    {"ref": "Mazmur 51:12", "isi": "Jadikanlah hatiku tahir, ya Allah, dan perbaharuilah batinku dengan roh yang teguh!"},
    {"ref": "Ibrani 13:8", "isi": "Yesus Kristus tetap sama, baik kemarin maupun hari ini dan sampai selama-lamanya."},
    {"ref": "Ratapan 3:22", "isi": "Tak berkesudahan kasih setia TUHAN, tak habis-habisnya rahmat-Nya."},
    {"ref": "Mazmur 37:5", "isi": "Serahkanlah hidupmu kepada TUHAN dan percayalah kepada-Nya, dan Ia akan bertindak."},
    {"ref": "Matius 28:20", "isi": "Dan ketahuilah, Aku menyertai kamu senantiasa sampai kepada akhir zaman."},
    {"ref": "Kisah Para Rasul 16:31", "isi": "Percayalah kepada Tuhan Yesus Kristus dan engkau akan selamat, engkau dan seisi rumahmu."},
    {"ref": "Yesaya 54:17", "isi": "Setiap senjata yang ditempa terhadap engkau tidak akan berhasil."},
    {"ref": "2 Korintus 5:17", "isi": "Jadi siapa yang ada di dalam Kristus, ia adalah ciptaan baru."},
    {"ref": "Mazmur 139:14", "isi": "Aku bersyukur kepada-Mu oleh karena kejadianku dahsyat dan ajaib."},
    {"ref": "Filipi 4:7", "isi": "Damai sejahtera Allah, yang melampaui segala akal, akan memelihara hati dan pikiranmu."},
    {"ref": "Amsal 3:6", "isi": "Akuilah Dia dalam segala lakumu, maka Ia akan meluruskan jalanmu."},
    {"ref": "Yohanes 8:12", "isi": "Akulah terang dunia; barangsiapa mengikut Aku, ia tidak akan berjalan dalam kegelapan."},
    {"ref": "Mazmur 145:18", "isi": "TUHAN dekat pada setiap orang yang berseru kepada-Nya dalam kesetiaan."},
    {"ref": "1 Yohanes 5:4", "isi": "Dan inilah kemenangan yang mengalahkan dunia: iman kita."},
    {"ref": "Wahyu 3:20", "isi": "Lihat, Aku berdiri di muka pintu dan mengetok."},
    {"ref": "Matius 5:7", "isi": "Berbahagialah orang yang murah hatinya, karena mereka akan beroleh kemurahan."},
    {"ref": "Mazmur 100:5", "isi": "Sebab TUHAN itu baik, kasih setia-Nya untuk selama-lamanya."},
    {"ref": "Amsal 15:1", "isi": "Jawaban yang lembut meredakan kegeraman."},
    {"ref": "Yohanes 10:10", "isi": "Aku datang, supaya mereka mempunyai hidup, dan mempunyainya dalam segala kelimpahan."},
    {"ref": "Habakuk 3:19", "isi": "ALLAH Tuhanku itu kekuatanku: Ia membuat kakiku seperti kaki rusa."},
    {"ref": "Mazmur 16:11", "isi": "Engkau memberitahukan kepadaku jalan kehidupan; di hadapan-Mu ada sukacita berlimpah-limpah."},
    {"ref": "1 Petrus 2:9", "isi": "Tetapi kamulah bangsa yang terpilih, imamat yang rajani, bangsa yang kudus."},
    {"ref": "Roma 8:31", "isi": "Jika Allah di pihak kita, siapakah yang akan melawan kita?"},
    {"ref": "Mazmur 119:11", "isi": "Dalam hatiku aku menyimpan janji-Mu, supaya aku jangan berdosa terhadap Engkau."},
    {"ref": "Filipi 2:14", "isi": "Lakukanlah segala sesuatu dengan tidak bersungut-sungut dan berbantah-bantahan."},
    {"ref": "Amsal 22:6", "isi": "Didiklah orang muda menurut jalan yang patut baginya, maka pada masa tuanyapun ia tidak akan menyimpang."},
    {"ref": "Yesaya 26:3", "isi": "Yang hatinya teguh Kaujagai dengan damai sejahtera, sebab kepada-Mulah ia percaya."},
    {"ref": "Yohanes 16:33", "isi": "Dalam dunia kamu menderita penganiayaan, tetapi kuatkanlah hatimu, Aku telah mengalahkan dunia."},
    {"ref": "Mazmur 126:5", "isi": "Orang-orang yang menabur dengan mencucurkan air mata, akan menuai dengan bersorak-sorai."},
    {"ref": "1 Korintus 13:13", "isi": "Demikianlah tinggal ketiga hal ini, yaitu iman, pengharapan dan kasih, dan yang paling besar di antaranya ialah kasih."},
    {"ref": "Mazmur 107:1", "isi": "Bersyukurlah kepada TUHAN, sebab Ia baik! Bahwasanya untuk selama-lamanya kasih setia-Nya."},
    {"ref": "Wahyu 21:4", "isi": "Dan Ia akan menghapus segala air mata dari mata mereka, dan maut tidak akan ada lagi."},
    {"ref": "Mazmur 34:10", "isi": "Takutlah akan TUHAN, hai orang-orang-Nya yang kudus, sebab tidak kekurangan orang yang takut akan Dia."},
    {"ref": "Ibrani 12:1", "isi": "Marilah kita menanggalkan semua beban dan dosa yang begitu merintangi kita."},
    {"ref": "Lukas 11:9", "isi": "Ketoklah, maka pintu akan dibukakan bagimu."},
    {"ref": "Mazmur 147:3", "isi": "Ia menyembuhkan orang-orang yang patah hati dan membalut luka-luka mereka."},
    {"ref": "2 Korintus 12:9", "isi": "Cukuplah kasih karunia-Ku bagimu, sebab di dalam kelemahanlah kuasa-Ku menjadi sempurna."},
    {"ref": "1 Yohanes 4:4", "isi": "Sebab Roh yang ada di dalam kamu, lebih besar dari pada roh yang ada di dalam dunia."},
    {"ref": "Mazmur 37:23", "isi": "TUHAN menetapkan langkah-langkah orang yang hidupnya berkenan kepada-Nya."},
    {"ref": "Roma 8:37", "isi": "Tetapi dalam semuanya itu kita lebih dari pada orang-orang yang menang, oleh Dia yang telah mengasihi kita."},
    {"ref": "Amsal 19:17", "isi": "Siapa menaruh belas kasihan kepada orang yang lemah, memiutangi TUHAN."},
    {"ref": "Matius 19:26", "isi": "Bagi manusia hal ini tidak mungkin, tetapi bagi Allah segala sesuatu mungkin."},
    {"ref": "Efesus 6:10", "isi": "Hendaklah kamu kuat di dalam Tuhan, di dalam kekuatan kuasa-Nya."},
    {"ref": "Mazmur 119:165", "isi": "Besar damai sejahtera pada orang-orang yang mencintai Taurat-Mu, tidak ada batu sandungan bagi mereka."},
    {"ref": "Kolose 3:17", "isi": "Dan segala sesuatu yang kamu lakukan dengan perkataan atau perbuatan, lakukanlah semuanya itu dalam nama Tuhan Yesus."},
    {"ref": "2 Tawarikh 7:14", "isi": "Dan umat-Ku, yang atasnya nama-Ku disebut, merendahkan diri, berdoa dan mencari wajah-Ku."},
    {"ref": "Amsal 3:27", "isi": "Janganlah menahan kebaikan dari pada orang yang berhak menerimanya, padahal engkau mampu melakukannya."},
    {"ref": "Mazmur 138:8", "isi": "TUHAN akan menyelesaikannya bagiku! Ya TUHAN, kasih setia-Mu untuk selama-lamanya."},
    {"ref": "Roma 12:1", "isi": "Persembahkanlah tubuhmu sebagai persembahan yang hidup, yang kudus dan yang berkenan kepada Allah."},
    {"ref": "1 Tesalonika 5:16", "isi": "Bersukacitalah senantiasa."},
    {"ref": "Mazmur 116:12", "isi": "Bagaimana akan kubalas kepada TUHAN segala kebajikan-Nya kepadaku?"},
    {"ref": "1 Yohanes 3:18", "isi": "Marilah kita mengasihi bukan dengan perkataan atau dengan lidah, tetapi dengan perbuatan dan dalam kebenaran."},
    {"ref": "Yohanes 15:16", "isi": "Bukan kamu yang memilih Aku, tetapi Akulah yang memilih kamu."},
    {"ref": "Mazmur 143:10", "isi": "Ajarlah aku melakukan kehendak-Mu, sebab Engkaulah Allahku!"},
    {"ref": "Roma 15:13", "isi": "Semoga Allah, sumber pengharapan, memenuhi kamu dengan segala sukacita dan damai sejahtera."},
    {"ref": "Amsal 16:9", "isi": "Hati manusia memikir-mikirkan jalannya, tetapi TUHANlah yang menentukan arah langkahnya."},
    {"ref": "Wahyu 2:10", "isi": "Hendaklah engkau setia sampai mati, dan Aku akan mengaruniakan kepadamu mahkota kehidupan."},
    {"ref": "Mazmur 31:25", "isi": "Kuatkanlah dan teguhkanlah hatimu, hai kamu semua yang berharap kepada TUHAN!"},
    {"ref": "Yakobus 1:2", "isi": "Anggaplah sebagai suatu kebahagiaan, apabila kamu jatuh ke dalam berbagai-bagai pencobaan."},
    {"ref": "Yohanes 1:12", "isi": "Tetapi semua orang yang menerima-Nya diberi-Nya kuasa supaya menjadi anak-anak Allah."},
    {"ref": "Mazmur 119:9", "isi": "Dengan apakah seorang muda mempertahankan kelakuannya bersih? Dengan menjaganya sesuai dengan firman-Mu."},
    {"ref": "1 Korintus 15:58", "isi": "Berdirilah teguh, jangan goyah, dan giatlah selalu dalam pekerjaan Tuhan!"},
    {"ref": "Yesaya 43:2", "isi": "Apabila engkau menyeberang melalui air, Aku akan menyertai engkau."},
    {"ref": "Matius 5:9", "isi": "Berbahagialah orang yang membawa damai, karena mereka akan disebut anak-anak Allah."},
    {"ref": "Mazmur 63:4", "isi": "Sebab kasih setia-Mu lebih baik dari pada hidup; bibirku akan memegahkan Engkau."},
    {"ref": "Roma 1:16", "isi": "Sebab aku mempunyai keyakinan yang kokoh dalam Injil, karena Injil adalah kekuatan Allah yang menyelamatkan."},
    {"ref": "Amsal 15:13", "isi": "Hati yang gembira memancarkan seri wajah, tetapi kepedihan hati mematahkan semangat."},
    {"ref": "Yohanes 4:24", "isi": "Allah itu Roh dan barangsiapa menyembah Dia, harus menyembah-Nya dalam roh dan kebenaran."},
    {"ref": "Mazmur 40:2", "isi": "Aku sangat menanti-nantikan TUHAN; lalu Ia menjenguk kepadaku dan mendengar teriakku minta tolong."},
    {"ref": "Filipi 4:8", "isi": "Semua yang benar, semua yang mulia, semua yang adil, semua yang suci, pikirkanlah semuanya itu."},
    {"ref": "1 Yohanes 5:14", "isi": "Dan inilah keberanian percaya kita kepada-Nya, yaitu bahwa Ia mengabulkan doa kita, jikalau kita meminta sesuatu sesuai kehendak-Nya."},
    {"ref": "Mazmur 111:10", "isi": "Permulaan hikmat adalah takut akan TUHAN."},
    {"ref": "2 Korintus 9:7", "isi": "Hendaklah masing-masing memberikan menurut kerelaan hatinya, sebab Allah mengasihi orang yang memberi dengan sukacita."},
    {"ref": "Matius 22:37", "isi": "Kasihilah Tuhan, Allahmu, dengan segenap hatimu dan dengan segenap jiwamu dan dengan segenap akal budimu."},
    {"ref": "Mazmur 34:1", "isi": "Aku hendak memuji TUHAN pada segala waktu; puji-pujian kepada-Nya tetap di dalam mulutku."},
    {"ref": "Lukas 12:31", "isi": "Tetapi carilah Kerajaan-Nya, maka semuanya itu akan ditambahkan juga kepadamu."},
    {"ref": "Yakobus 5:16", "isi": "Doa orang yang benar, bila dengan yakin didoakan, sangat besar kuasanya."},
    {"ref": "Mazmur 119:18", "isi": "Singkapkanlah mataku, supaya aku memandang keajaiban-keajaiban dari Taurat-Mu."},
    {"ref": "1 Petrus 3:15", "isi": "Tetapi kuduskanlah Kristus di dalam hatimu sebagai Tuhan!"},
    {"ref": "Roma 12:2", "isi": "Janganlah kamu menjadi serupa dengan dunia ini, tetapi berubahlah oleh pembaharuan budimu."},
    {"ref": "Matius 18:20", "isi": "Sebab di mana dua atau tiga orang berkumpul dalam Nama-Ku, di situ Aku ada di tengah-tengah mereka."},
    {"ref": "Mazmur 103:2", "isi": "Pujilah TUHAN, hai jiwaku, dan janganlah lupakan segala kebaikan-Nya!"},
    {"ref": "Efesus 6:11", "isi": "Kenakanlah seluruh perlengkapan senjata Allah, supaya kamu dapat bertahan melawan tipu muslihat Iblis."},
    {"ref": "Amsal 14:27", "isi": "Takut akan TUHAN adalah sumber kehidupan."},
    {"ref": "Yohanes 13:34", "isi": "Aku memberikan perintah baru kepada kamu, yaitu supaya kamu saling mengasihi."},
    {"ref": "Mazmur 90:12", "isi": "Ajarlah kami menghitung hari-hari kami sedemikian, hingga kami beroleh hati yang bijaksana."},
    {"ref": "Matius 6:34", "isi": "Sebab itu janganlah kamu kuatir akan hari besok, karena hari besok mempunyai kesusahannya sendiri."},
    {"ref": "2 Korintus 3:17", "isi": "Sebab Tuhan adalah Roh; dan di mana ada Roh Allah, di situ ada kemerdekaan."},
    {"ref": "Mazmur 56:4", "isi": "Waktu aku takut, aku ini percaya kepada-Mu."},
    {"ref": "Filipi 1:6", "isi": "Ia, yang memulai pekerjaan yang baik di antara kamu, akan meneruskannya sampai pada akhirnya."},
    {"ref": "Lukas 18:27", "isi": "Apa yang tidak mungkin bagi manusia, mungkin bagi Allah."},
    {"ref": "Yakobus 1:22", "isi": "Tetapi hendaklah kamu menjadi pelaku firman dan bukan hanya pendengar saja."},
    {"ref": "Mazmur 103:13", "isi": "Seperti bapa sayang kepada anak-anaknya, demikian TUHAN sayang kepada orang-orang yang takut akan Dia."},
    {"ref": "Roma 8:38", "isi": "Sebab aku yakin, bahwa baik maut, maupun hidup tidak akan dapat memisahkan kita dari kasih Allah."},
    {"ref": "Amsal 27:19", "isi": "Seperti air mencerminkan wajah, demikianlah hati manusia mencerminkan manusia itu."},
    {"ref": "1 Korintus 13:4", "isi": "Kasih itu sabar; kasih itu murah hati; ia tidak cemburu. Ia tidak memegahkan diri dan tidak sombong."},
    {"ref": "Mazmur 115:11", "isi": "Hai orang-orang yang takut akan TUHAN, percayalah kepada TUHAN! Dialah pertolongan mereka dan perisai mereka."},
    {"ref": "Ibrani 10:24", "isi": "Dan marilah kita saling memperhatikan supaya kita saling mendorong dalam kasih dan dalam perbuatan baik."},
    {"ref": "Matius 24:13", "isi": "Tetapi orang yang bertahan sampai pada kesudahannya akan selamat."},
    {"ref": "Mazmur 119:50", "isi": "Inilah penghiburanku dalam sengsaraku, bahwa janji-Mu menghidupkan aku."},
    {"ref": "1 Yohanes 4:18", "isi": "Di dalam kasih tidak ada ketakutan: kasih yang sempurna melenyapkan ketakutan."},
    {"ref": "Roma 6:23", "isi": "Sebab upah dosa ialah maut; tetapi karunia Allah ialah hidup yang kekal dalam Kristus Yesus, Tuhan kita."},
    {"ref": "Amsal 13:20", "isi": "Siapa berjalan dengan orang bijak menjadi bijak, tetapi siapa berteman dengan orang bebal menjadi malang."},
    {"ref"