import 'dart:math';

class AyatData {
  static final List<Map<String, String>> daftarAyat = [
    {"ref": "Mazmur 23:1", "isi": "TUHAN adalah gembalaku, takkan kekurangan aku."},
    {"ref": "Yesaya 41:10", "isi": "Janganlah takut, sebab Aku menyertai engkau, janganlah bimbang, sebab Aku ini Allahmu."},
    {"ref": "Filipi 4:13", "isi": "Segala perkara dapat kutanggung di dalam Dia yang memberi kekuatan kepadaku."},
    {"ref": "Yosua 1:9", "isi": "Kuatkan dan teguhkanlah hatimu! Janganlah kecut dan tawar hati, sebab TUHAN menyertai engkau."},
    {"ref": "Mazmur 46:2", "isi": "Allah itu bagi kita tempat perlindungan dan kekuatan, sebagai penolong dalam kesesakan."},
    {"ref": "Nahum 1:7", "isi": "TUHAN itu baik; Ia adalah tempat pengungsian pada waktu kesusahan."},
    {"ref": "Yesaya 40:31", "isi": "Orang yang menanti-nantikan TUHAN mendapat kekuatan baru: seumpama rajawali yang terbang."},
    {"ref": "2 Timotius 1:7", "isi": "Sebab Allah memberikan bukan roh ketakutan, melainkan roh kekuatan, kasih dan ketertiban."},
    {"ref": "Mazmur 27:1", "isi": "TUHAN adalah terangku dan keselamatanku, kepada siapakah aku harus takut?"},
    {"ref": "Amsal 18:10", "isi": "Nama TUHAN adalah menara yang kuat, ke sanalah orang benar lari dan ia menjadi aman."},
    {"ref": "Mazmur 91:1", "isi": "Orang yang duduk dalam lindungan Yang Mahatinggi akan bermalam dalam naungan Yang Mahakuasa."},
    {"ref": "Keluaran 14:14", "isi": "TUHAN akan berperang untuk kamu, dan kamu akan diam saja."},
    {"ref": "Mazmur 121:2", "isi": "Pertolonganku ialah dari TUHAN, yang menjadikan langit dan bumi."},
    {"ref": "Zefanya 3:17", "isi": "TUHAN Allahmu ada di antaramu sebagai pahlawan yang memberi kemenangan."},
    {"ref": "2 Tesalonika 3:3", "isi": "Tetapi Tuhan adalah setia. Ia akan menguatkan hatimu dan memelihara kamu terhadap yang jahat."},
    {"ref": "Yohanes 3:16", "isi": "Karena begitu besar kasih Allah akan dunia ini, sehingga Ia mengaruniakan Anak-Nya yang tunggal."},
    {"ref": "1 Yohanes 4:19", "isi": "Kita mengasihi, karena Allah lebih dahulu mengasihi kita."},
    {"ref": "Roma 5:8", "isi": "Akan tetapi Allah menunjukkan kasih-Nya kepada kita, oleh karena Kristus telah mati untuk kita."},
    {"ref": "Efesus 4:32", "isi": "Hendaklah kamu ramah, penuh kasih mesra dan saling mengampuni."},
    {"ref": "1 Korintus 16:14", "isi": "Lakukanlah segala pekerjaanmu dalam kasih!"},
    {"ref": "1 Yohanes 1:9", "isi": "Jika kita mengaku dosa kita, maka Ia adalah setia dan adil, sehingga Ia mengampuni segala dosa kita."},
    {"ref": "Mazmur 103:8", "isi": "TUHAN adalah penyayang dan pengasih, panjang sabar dan berlimpah kasih setia."},
    {"ref": "Yeremia 31:3", "isi": "Aku mengasihi engkau dengan kasih yang kekal, sebab itu Aku melanjutkan kasih setia-Ku kepadamu."},
    {"ref": "Yohanes 15:13", "isi": "Tidak ada kasih yang lebih besar dari pada kasih seorang yang memberikan nyawanya untuk sahabatnya."},
    {"ref": "1 Petrus 4:8", "isi": "Sebab kasih menutupi banyak sekali dosa."},
    {"ref": "Yeremia 29:11", "isi": "Sebab Aku tahu rancangan-rancangan apa yang ada pada-Ku, yaitu rancangan damai sejahtera."},
    {"ref": "Matius 6:33", "isi": "Tetapi carilah dahulu Kerajaan Allah, maka semuanya itu akan ditambahkan kepadamu."},
    {"ref": "Amsal 16:3", "isi": "Serahkanlah perbuatanmu kepada TUHAN, maka terlaksanalah segala rencanamu."},
    {"ref": "Malakhi 3:10", "isi": "Bawalah seluruh persembahan persepuluhan, supaya ada persediaan makanan di rumah-Ku."},
    {"ref": "Ulangan 28:2", "isi": "Segala berkat ini akan datang kepadamu dan menjadi bagianmu, asal engkau mendengarkan suara TUHAN."},
    {"ref": "Mazmur 37:4", "isi": "Bergembiralah karena TUHAN; maka Ia akan memberikan kepadamu apa yang diinginkan hatimu."},
    {"ref": "Filipi 4:19", "isi": "Allahku akan memenuhi segala keperluanmu menurut kekayaan dan kemuliaan-Nya dalam Kristus Yesus."},
    {"ref": "Amsal 10:22", "isi": "Berkat TUHANlah yang menjadikan kaya, susah payah tidak akan menambahinya."},
    {"ref": "Bilangan 6:24", "isi": "TUHAN memberkati engkau dan melindungi engkau."},
    {"ref": "Mazmur 1:3", "isi": "Ia seumpama pohon, yang ditanam di tepi aliran air, yang menghasilkan buahnya pada musimnya."},
    {"ref": "Ibrani 11:1", "isi": "Iman adalah dasar dari segala sesuatu yang kita harapkan dan bukti dari yang tidak kita lihat."},
    {"ref": "Markus 11:24", "isi": "Apa saja yang kamu minta dan doakan, percayalah bahwa kamu telah menerimanya."},
    {"ref": "Lukas 1:37", "isi": "Sebab bagi Allah tidak ada yang mustahil."},
    {"ref": "Matius 7:7", "isi": "Mintalah, maka akan diberikan kepadamu; carilah, maka kamu akan mendapat."},
    {"ref": "Yakobus 1:5", "isi": "Apabila di antara kamu ada yang kekurangan hikmat, hendaklah ia memintakannya kepada Allah."},
    {"ref": "Ibrani 4:16", "isi": "Marilah kita dengan penuh keberanian menghampiri takhta kasih karunia."},
    {"ref": "Roma 10:17", "isi": "Jadi, iman timbul dari pendengaran, dan pendengaran oleh firman Kristus."},
    {"ref": "1 Petrus 5:7", "isi": "Serahkanlah segala kekuatiranmu kepada-Nya, sebab Ia yang memelihara kamu."},
    {"ref": "Mazmur 34:18", "isi": "Apabila orang-orang benar itu berseru-seru, maka TUHAN mendengar."},
    {"ref": "Yeremia 33:3", "isi": "Berserulah kepada-Ku, maka Aku akan menjawab engkau."},
    {"ref": "Mazmur 119:105", "isi": "Firman-Mu itu pelita bagi kakiku dan terang bagi jalanku."},
    {"ref": "Amsal 4:23", "isi": "Jagalah hatimu dengan segala kewaspadaan, karena dari situlah terpancar kehidupan."},
    {"ref": "Pengkhotbah 3:11", "isi": "Ia membuat segala sesuatu indah pada waktunya."},
    {"ref": "Kolose 3:23", "isi": "Apapun juga yang kamu perbuat, perbuatlah dengan segenap hatimu seperti untuk Tuhan."},
    {"ref": "1 Tesalonika 5:18", "isi": "Mengucap syukurlah dalam segala hal, sebab itulah yang dikehendaki Allah."},
    {"ref": "Matius 5:16", "isi": "Demikianlah hendaknya terangmu bercahaya, supaya mereka melihat perbuatanmu yang baik."},
    {"ref": "Galatia 5:22", "isi": "Tetapi buah Roh ialah: kasih, sukacita, damai sejahtera, kesabaran, kemurahan, kebaikan, kesetiaan."},
    {"ref": "Roma 12:21", "isi": "Janganlah kamu kalah terhadap kejahatan, tetapi kalahkanlah kejahatan dengan kebaikan!"},
    {"ref": "Mazmur 118:24", "isi": "Inilah hari yang dijadikan TUHAN, marilah kita bersorak-sorak dan bersukacita."},
    {"ref": "Amsal 17:17", "isi": "Seorang sahabat menaruh kasih setiap waktu, dan menjadi seorang saudara dalam kesukaran."},
    {"ref": "Yohanes 14:6", "isi": "Akulah jalan dan kebenaran dan hidup. Tidak ada seorangpun yang datang kepada Bapa, kalau tidak melalui Aku."},
    {"ref": "Lukas 6:31", "isi": "Dan sebagaimana kamu kehendaki supaya orang perbuat kepadamu, perbuatlah juga demikian kepada mereka."},
    {"ref": "Yakobus 4:7", "isi": "Karena itu tunduklah kepada Allah, dan lawanlah Iblis, maka ia akan lari dari padamu!"},
    {"ref": "Roma 12:12", "isi": "Bersukacitalah dalam pengharapan, sabarlah dalam kesesakan, dan bertekunlah dalam doa!"},
    {"ref": "1 Korintus 10:13", "isi": "Pencobaan yang kamu alami ialah pencobaan biasa, yang tidak melebihi kekuatan manusia."},
    {"ref": "Yosua 24:15", "isi": "Tetapi aku dan seisi rumahku, kami akan beribadah kepada TUHAN!"},
    {"ref": "Mazmur 34:8", "isi": "Kecaplah dan lihatlah, betapa baiknya TUHAN itu!"},
    {"ref": "Efesus 2:8", "isi": "Sebab karena kasih karunia kamu diselamatkan oleh iman."},
    {"ref": "Mazmur 51:12", "isi": "Jadikanlah hatiku tahir, ya Allah, dan perbaharuilah batinku dengan roh yang teguh!"},
    {"ref": "Ibrani 13:8", "isi": "Yesus Kristus tetap sama, baik kemarin maupun hari ini dan sampai selama-lamanya."},
    {"ref": "Ratapan 3:22", "isi": "Tak berkesudahan kasih setia TUHAN, tak habis-habisnya rahmat-Nya."},
    {"ref": "Mazmur 37:5", "isi": "Serahkanlah hidupmu kepada TUHAN dan percayalah kepada-Nya, dan Ia akan bertindak."},
    {"ref": "Matius 28:20", "isi": "Dan ketahuilah, Aku menyertai kamu senantiasa sampai kepada akhir zaman."},
    {"ref": "Kisah Para Rasul 16:31", "isi": "Percayalah kepada Tuhan Yesus Kristus dan engkau akan selamat, engkau dan seisi rumahmu."},
    {"ref": "Yesaya 54:17", "isi": "Setiap senjata yang ditempa terhadap engkau tidak akan berhasil."},
    {"ref": "2 Korintus 5:17", "isi": "Jadi siapa yang ada di dalam Kristus, ia adalah ciptaan baru."},
    {"ref": "Mazmur 139:14", "isi": "Aku bersyukur kepada-Mu oleh karena kejadianku dahsyat dan ajaib."},
    {"ref": "Filipi 4:7", "isi": "Damai sejahtera Allah, yang melampaui segala akal, akan memelihara hati dan pikiranmu."},
    {"ref": "Amsal 3:6", "isi": "Akuilah Dia dalam segala lakumu, maka Ia akan meluruskan jalanmu."},
    {"ref": "Yohanes 8:12", "isi": "Akulah terang dunia; barangsiapa mengikut Aku, ia tidak akan berjalan dalam kegelapan."},
    {"ref": "Mazmur 145:18", "isi": "TUHAN dekat pada setiap orang yang berseru kepada-Nya dalam kesetiaan."},
    {"ref": "1 Yohanes 5:4", "isi": "Dan inilah kemenangan yang mengalahkan dunia: iman kita."},
    {"ref": "Wahyu 3:20", "isi": "Lihat, Aku berdiri di muka pintu dan mengetok."},
    {"ref": "Matius 5:7", "isi": "Berbahagialah orang yang murah hatinya, karena mereka akan beroleh kemurahan."},
    {"ref": "Mazmur 100:5", "isi": "Sebab TUHAN itu baik, kasih setia-Nya untuk selama-lamanya."},
    {"ref": "Amsal 15:1", "isi": "Jawaban yang lembut meredakan kegeraman."},
    {"ref": "Yohanes 10:10", "isi": "Aku datang, supaya mereka mempunyai hidup, dan mempunyainya dalam segala kelimpahan."},
    {"ref": "Habakuk 3:19", "isi": "ALLAH Tuhanku itu kekuatanku: Ia membuat kakiku seperti kaki rusa."},
    {"ref": "Mazmur 16:11", "isi": "Engkau memberitahukan kepadaku jalan kehidupan; di hadapan-Mu ada sukacita berlimpah-limpah."},
    {"ref": "1 Petrus 2:9", "isi": "Tetapi kamulah bangsa yang terpilih, imamat yang rajani, bangsa yang kudus."},
    {"ref": "Roma 8:31", "isi": "Jika Allah di pihak kita, siapakah yang akan melawan kita?"},
    {"ref": "Mazmur 119:11", "isi": "Dalam hatiku aku menyimpan janji-Mu, supaya aku jangan berdosa terhadap Engkau."},
    {"ref": "Filipi 2:14", "isi": "Lakukanlah segala sesuatu dengan tidak bersungut-sungut dan berbantah-bantahan."},
    {"ref": "Amsal 22:6", "isi": "Didiklah orang muda menurut jalan yang patut baginya, maka pada masa tuanyapun ia tidak akan menyimpang."},
    {"ref": "Yesaya 26:3", "isi": "Yang hatinya teguh Kaujagai dengan damai sejahtera, sebab kepada-Mulah ia percaya."},
    {"ref": "Yohanes 16:33", "isi": "Dalam dunia kamu menderita penganiayaan, tetapi kuatkanlah hatimu, Aku telah mengalahkan dunia."},
    {"ref": "Mazmur 126:5", "isi": "Orang-orang yang menabur dengan mencucurkan air mata, akan menuai dengan bersorak-sorai."},
    {"ref": "1 Korintus 13:13", "isi": "Demikianlah tinggal ketiga hal ini, yaitu iman, pengharapan dan kasih, dan yang paling besar di antaranya ialah kasih."},
    {"ref": "Mazmur 107:1", "isi": "Bersyukurlah kepada TUHAN, sebab Ia baik! Bahwasanya untuk selama-lamanya kasih setia-Nya."},
    {"ref": "Wahyu 21:4", "isi": "Dan Ia akan menghapus segala air mata dari mata mereka, dan maut tidak akan ada lagi."},
    {"ref": "Mazmur 34:10", "isi": "Takutlah akan TUHAN, hai orang-orang-Nya yang kudus, sebab tidak kekurangan orang yang takut akan Dia."},
    {"ref": "Ibrani 12:1", "isi": "Marilah kita menanggalkan semua beban dan dosa yang begitu merintangi kita."},
    {"ref": "Lukas 11:9", "isi": "Ketoklah, maka pintu akan dibukakan bagimu."},
    {"ref": "Mazmur 147:3", "isi": "Ia menyembuhkan orang-orang yang patah hati dan membalut luka-luka mereka."},
    {"ref": "2 Korintus 12:9", "isi": "Cukuplah kasih karunia-Ku bagimu, sebab di dalam kelemahanlah kuasa-Ku menjadi sempurna."},
    {"ref": "1 Yohanes 4:4", "isi": "Sebab Roh yang ada di dalam kamu, lebih besar dari pada roh yang ada di dalam dunia."},
    {"ref": "Mazmur 37:23", "isi": "TUHAN menetapkan langkah-langkah orang yang hidupnya berkenan kepada-Nya."},
    {"ref": "Roma 8:37", "isi": "Tetapi dalam semuanya itu kita lebih dari pada orang-orang yang menang, oleh Dia yang telah mengasihi kita."},
    {"ref": "Amsal 19:17", "isi": "Siapa menaruh belas kasihan kepada orang yang lemah, memiutangi TUHAN."},
    {"ref": "Matius 19:26", "isi": "Bagi manusia hal ini tidak mungkin, tetapi bagi Allah segala sesuatu mungkin."},
    {"ref": "Efesus 6:10", "isi": "Hendaklah kamu kuat di dalam Tuhan, di dalam kekuatan kuasa-Nya."},
    {"ref": "Mazmur 119:165", "isi": "Besar damai sejahtera pada orang-orang yang mencintai Taurat-Mu, tidak ada batu sandungan bagi mereka."},
    {"ref": "Kolose 3:17", "isi": "Dan segala sesuatu yang kamu lakukan dengan perkataan atau perbuatan, lakukanlah semuanya itu dalam nama Tuhan Yesus."},
    {"ref": "2 Tawarikh 7:14", "isi": "Dan umat-Ku, yang atasnya nama-Ku disebut, merendahkan diri, berdoa dan mencari wajah-Ku."},
    {"ref": "Amsal 3:27", "isi": "Janganlah menahan kebaikan dari pada orang yang berhak menerimanya, padahal engkau mampu melakukannya."},
    {"ref": "Mazmur 138:8", "isi": "TUHAN akan menyelesaikannya bagiku! Ya TUHAN, kasih setia-Mu untuk selama-lamanya."},
    {"ref": "Roma 12:1", "isi": "Persembahkanlah tubuhmu sebagai persembahan yang hidup, yang kudus dan yang berkenan kepada Allah."},
    {"ref": "1 Tesalonika 5:16", "isi": "Bersukacitalah senantiasa."},
    {"ref": "Mazmur 116:12", "isi": "Bagaimana akan kubalas kepada TUHAN segala kebajikan-Nya kepadaku?"},
    {"ref": "1 Yohanes 3:18", "isi": "Marilah kita mengasihi bukan dengan perkataan atau dengan lidah, tetapi dengan perbuatan dan dalam kebenaran."},
    {"ref": "Yohanes 15:16", "isi": "Bukan kamu yang memilih Aku, tetapi Akulah yang memilih kamu."},
    {"ref": "Mazmur 143:10", "isi": "Ajarlah aku melakukan kehendak-Mu, sebab Engkaulah Allahku!"},
    {"ref": "Roma 15:13", "isi": "Semoga Allah, sumber pengharapan, memenuhi kamu dengan segala sukacita dan damai sejahtera."},
    {"ref": "Amsal 16:9", "isi": "Hati manusia memikir-mikirkan jalannya, tetapi TUHANlah yang menentukan arah langkahnya."},
    {"ref": "Wahyu 2:10", "isi": "Hendaklah engkau setia sampai mati, dan Aku akan mengaruniakan kepadamu mahkota kehidupan."},
    {"ref": "Mazmur 31:25", "isi": "Kuatkanlah dan teguhkanlah hatimu, hai kamu semua yang berharap kepada TUHAN!"},
    {"ref": "Yakobus 1:2", "isi": "Anggaplah sebagai suatu kebahagiaan, apabila kamu jatuh ke dalam berbagai-bagai pencobaan."},
    {"ref": "Yohanes 1:12", "isi": "Tetapi semua orang yang menerima-Nya diberi-Nya kuasa supaya menjadi anak-anak Allah."},
    {"ref": "Mazmur 119:9", "isi": "Dengan apakah seorang muda mempertahankan kelakuannya bersih? Dengan menjaganya sesuai dengan firman-Mu."},
    {"ref": "1 Korintus 15:58", "isi": "Berdirilah teguh, jangan goyah, dan giatlah selalu dalam pekerjaan Tuhan!"},
    {"ref": "Yesaya 43:2", "isi": "Apabila engkau menyeberang melalui air, Aku akan menyertai engkau."},
    {"ref": "Matius 5:9", "isi": "Berbahagialah orang yang membawa damai, karena mereka akan disebut anak-anak Allah."},
    {"ref": "Mazmur 63:4", "isi": "Sebab kasih setia-Mu lebih baik dari pada hidup; bibirku akan memegahkan Engkau."},
    {"ref": "Roma 1:16", "isi": "Sebab aku mempunyai keyakinan yang kokoh dalam Injil, karena Injil adalah kekuatan Allah yang menyelamatkan."},
    {"ref": "Amsal 15:13", "isi": "Hati yang gembira memancarkan seri wajah, tetapi kepedihan hati mematahkan semangat."},
    {"ref": "Yohanes 4:24", "isi": "Allah itu Roh dan barangsiapa menyembah Dia, harus menyembah-Nya dalam roh dan kebenaran."},
    {"ref": "Mazmur 40:2", "isi": "Aku sangat menanti-nantikan TUHAN; lalu Ia menjenguk kepadaku dan mendengar teriakku minta tolong."},
    {"ref": "Filipi 4:8", "isi": "Semua yang benar, semua yang mulia, semua yang adil, semua yang suci, pikirkanlah semuanya itu."},
    {"ref": "1 Yohanes 5:14", "isi": "Dan inilah keberanian percaya kita kepada-Nya, yaitu bahwa Ia mengabulkan doa kita, jikalau kita meminta sesuatu sesuai kehendak-Nya."},
    {"ref": "Mazmur 111:10", "isi": "Permulaan hikmat adalah takut akan TUHAN."},
    {"ref": "2 Korintus 9:7", "isi": "Hendaklah masing-masing memberikan menurut kerelaan hatinya, sebab Allah mengasihi orang yang memberi dengan sukacita."},
    {"ref": "Matius 22:37", "isi": "Kasihilah Tuhan, Allahmu, dengan segenap hatimu dan dengan segenap jiwamu dan dengan segenap akal budimu."},
    {"ref": "Mazmur 34:1", "isi": "Aku hendak memuji TUHAN pada segala waktu; puji-pujian kepada-Nya tetap di dalam mulutku."},
    {"ref": "Lukas 12:31", "isi": "Tetapi carilah Kerajaan-Nya, maka semuanya itu akan ditambahkan juga kepadamu."},
    {"ref": "Yakobus 5:16", "isi": "Doa orang yang benar, bila dengan yakin didoakan, sangat besar kuasanya."},
    {"ref": "Mazmur 119:18", "isi": "Singkapkanlah mataku, supaya aku memandang keajaiban-keajaiban dari Taurat-Mu."},
    {"ref": "1 Petrus 3:15", "isi": "Tetapi kuduskanlah Kristus di dalam hatimu sebagai Tuhan!"},
    {"ref": "Roma 12:2", "isi": "Janganlah kamu menjadi serupa dengan dunia ini, tetapi berubahlah oleh pembaharuan budimu."},
    {"ref": "Matius 18:20", "isi": "Sebab di mana dua atau tiga orang berkumpul dalam Nama-Ku, di situ Aku ada di tengah-tengah mereka."},
    {"ref": "Mazmur 103:2", "isi": "Pujilah TUHAN, hai jiwaku, dan janganlah lupakan segala kebaikan-Nya!"},
    {"ref": "Efesus 6:11", "isi": "Kenakanlah seluruh perlengkapan senjata Allah, supaya kamu dapat bertahan melawan tipu muslihat Iblis."},
    {"ref": "Amsal 14:27", "isi": "Takut akan TUHAN adalah sumber kehidupan."},
    {"ref": "Yohanes 13:34", "isi": "Aku memberikan perintah baru kepada kamu, yaitu supaya kamu saling mengasihi."},
    {"ref": "Mazmur 90:12", "isi": "Ajarlah kami menghitung hari-hari kami sedemikian, hingga kami beroleh hati yang bijaksana."},
    {"ref": "Matius 6:34", "isi": "Sebab itu janganlah kamu kuatir akan hari besok, karena hari besok mempunyai kesusahannya sendiri."},
    {"ref": "2 Korintus 3:17", "isi": "Sebab Tuhan adalah Roh; dan di mana ada Roh Allah, di situ ada kemerdekaan."},
    {"ref": "Mazmur 56:4", "isi": "Waktu aku takut, aku ini percaya kepada-Mu."},
    {"ref": "Filipi 1:6", "isi": "Ia, yang memulai pekerjaan yang baik di antara kamu, akan meneruskannya sampai pada akhirnya."},
    {"ref": "Lukas 18:27", "isi": "Apa yang tidak mungkin bagi manusia, mungkin bagi Allah."},
    {"ref": "Yakobus 1:22", "isi": "Tetapi hendaklah kamu menjadi pelaku firman dan bukan hanya pendengar saja."},
    {"ref": "Mazmur 103:13", "isi": "Seperti bapa sayang kepada anak-anaknya, demikian TUHAN sayang kepada orang-orang yang takut akan Dia."},
    {"ref": "Roma 8:38", "isi": "Sebab aku yakin, bahwa baik maut, maupun hidup tidak akan dapat memisahkan kita dari kasih Allah."},
    {"ref": "Amsal 27:19", "isi": "Seperti air mencerminkan wajah, demikianlah hati manusia mencerminkan manusia itu."},
    {"ref": "1 Korintus 13:4", "isi": "Kasih itu sabar; kasih itu murah hati; ia tidak cemburu. Ia tidak memegahkan diri dan tidak sombong."},
    {"ref": "Mazmur 115:11", "isi": "Hai orang-orang yang takut akan TUHAN, percayalah kepada TUHAN! Dialah pertolongan mereka dan perisai mereka."},
    {"ref": "Ibrani 10:24", "isi": "Dan marilah kita saling memperhatikan supaya kita saling mendorong dalam kasih dan dalam perbuatan baik."},
    {"ref": "Matius 24:13", "isi": "Tetapi orang yang bertahan sampai pada kesudahannya akan selamat."},
    {"ref": "Mazmur 119:50", "isi": "Inilah penghiburanku dalam sengsaraku, bahwa janji-Mu menghidupkan aku."},
    {"ref": "1 Yohanes 4:18", "isi": "Di dalam kasih tidak ada ketakutan: kasih yang sempurna melenyapkan ketakutan."},
    {"ref": "Roma 6:23", "isi": "Sebab upah dosa ialah maut; tetapi karunia Allah ialah hidup yang kekal dalam Kristus Yesus, Tuhan kita."},
    {"ref": "Amsal 13:20", "isi": "Siapa berjalan dengan orang bijak menjadi bijak, tetapi siapa berteman dengan orang bebal menjadi malang."},
    {"ref": "Yohanes 15:7", "isi": "Jikalau kamu tinggal di dalam Aku dan firman-Ku tinggal di dalam kamu, mintalah apa saja yang kamu kehendaki."},
    {"ref": "Mazmur 37:7", "isi": "Berdiam dirilah di hadapan TUHAN dan nantikanlah Dia."},
    {"ref": "Filipi 3:14", "isi": "Dan berlari-lari kepada tujuan untuk memperoleh hadiah, yaitu panggilan sorgawi dari Allah dalam Kristus Yesus."},
    {"ref": "Lukas 11:28", "isi": "Yang berbahagia ialah mereka yang mendengarkan firman Allah dan yang memeliharanya."},
    {"ref": "Matius 5:8", "isi": "Berbahagialah orang yang suci hatinya, karena mereka akan melihat Allah."},
    {"ref": "Mazmur 119:160", "isi": "Dasar firman-Mu adalah kebenaran dan segala hukum-hukum-Mu yang adil adalah untuk selama-lamanya."},
    {"ref": "1 Petrus 5:10", "isi": "Dan Allah, sumber segala kasih karunia, akan melengkapi, meneguhkan, menguatkan dan mengkokohkan kamu."},
    {"ref": "Roma 12:15", "isi": "Bersukacitalah dengan orang yang bersukacita, dan menangislah dengan orang yang menangis!"},
    {"ref": "Amsal 10:19", "isi": "Di dalam banyak bicara pasti ada pelanggaran, tetapi siapa yang menahan bibirnya, berakal budi."},
    {"ref": "Mazmur 113:3", "isi": "Dari terbitnya sampai kepada terbenamnya matahari terpujilah nama TUHAN."},
    {"ref": "1 Yohanes 2:17", "isi": "Dan dunia ini sedang lenyap dengan keinginannya, tetapi orang yang melakukan kehendak Allah tetap hidup selama-lamanya."},
    {"ref": "Efesus 5:16", "isi": "Dan gunakanlah waktu yang ada, karena hari-hari ini adalah jahat."},
    {"ref": "Matius 16:24", "isi": "Setiap orang yang mau mengikut Aku, ia harus menyangkal dirinya, memikul salibnya dan mengikut Aku."},
    {"ref": "Mazmur 145:9", "isi": "TUHAN itu baik kepada semua orang, dan penuh rahmat terhadap segala buatan-Nya."},
    {"ref": "Kolose 3:15", "isi": "Hendaklah damai sejahtera Kristus memerintah dalam hatimu."},
    {"ref": "2 Timotius 3:16", "isi": "Segala tulisan yang diilhamkan Allah memang bermanfaat untuk mengajar, untuk menyatakan kesalahan."},
    {"ref": "Mazmur 25:4", "isi": "Beritahukanlah jalan-jalan-Mu kepadaku, ya TUHAN, tunjukkanlah lorong-lorong-Mu kepadaku."},
    {"ref": "Filipi 4:11", "isi": "Aku telah belajar mencukupkan diri dalam segala keadaan."},
    {"ref": "Matius 11:29", "isi": "Pikullah kuk yang Kupasang dan belajarlah pada-Ku, karena Aku lemah lembut dan rendah hati."},
    {"ref": "Mazmur 30:6", "isi": "Sepanjang malam ada tangisan, menjelang pagi terdengar sorak-sorai."},
    {"ref": "1 Korintus 16:13", "isi": "Berjaga-jagalah! Berdirilah dengan teguh dalam iman! Jadilah laki-laki! Dan jadilah kuat!"},
    {"ref": "Yohanes 6:35", "isi": "Akulah roti hidup; barangsiapa datang kepada-Ku, ia tidak akan lapar lagi."},
    {"ref": "Mazmur 146:5", "isi": "Berbahagialah orang yang mempunyai Allah Yakub sebagai penolong, yang harapannya pada TUHAN, Allahnya."},
    {"ref": "Lukas 21:19", "isi": "Kalau kamu tetap bertahan, kamu akan memperoleh hidupmu."},
    {"ref": "Amsal 14:1", "isi": "Perempuan yang bijak mendirikan rumahnya, tetapi yang bodoh meruntuhkannya dengan tangannya sendiri."},
    {"ref": "Yohanes 14:1", "isi": "Janganlah gelisah hatimu; percayalah kepada Allah, percayalah juga kepada-Ku."},
    {"ref": "Mazmur 119:111", "isi": "Peringatan-peringatan-Mu adalah milik pusakaku untuk selama-lamanya, sebab semuanya itu kegirangan hatiku."},
    {"ref": "1 Petrus 3:12", "isi": "Sebab mata Tuhan tertuju kepada orang-orang benar, dan telinga-Nya kepada doa mereka."},
    {"ref": "Roma 8:1", "isi": "Demikianlah sekarang tidak ada penghukuman bagi mereka yang ada di dalam Kristus Yesus."},
    {"ref": "Amsal 16:24", "isi": "Perkataan yang menyenangkan adalah seperti sarang madu, manis bagi hati dan obat bagi tulang-tulang."},
    {"ref": "Yesaya 40:29", "isi": "Dia memberi kekuatan kepada yang lelah dan menambah semangat kepada yang tiada berdaya."},
    {"ref": "Mazmur 18:31", "isi": "Adapun Allah, jalan-Nya sempurna; janji TUHAN adalah murni; Ia menjadi perisai bagi semua orang yang berlindung pada-Nya."},
    {"ref": "Matius 5:3", "isi": "Berbahagialah orang yang miskin di hadapan Allah, karena merekalah yang empunya Kerajaan Sorga."},
    {"ref": "Yohanes 17:17", "isi": "Kuduskanlah mereka dalam kebenaran; firman-Mu adalah kebenaran."},
    {"ref": "Mazmur 37:3", "isi": "Percayalah kepada TUHAN dan lakukanlah yang baik, diamlah di negeri dan berlakulah setia."},
    {"ref": "Ibrani 13:5", "isi": "Janganlah kamu menjadi hamba uang dan cukupkanlah dirimu dengan apa yang ada padamu."},
    {"ref": "Amsal 3:7", "isi": "Janganlah engkau menganggap dirimu sendiri bijak, takutlah akan TUHAN dan jauhilah kejahatan."},
    {"ref": "Yesaya 43:1", "isi": "Janganlah takut, sebab Aku telah menebus engkau, Aku telah memanggil engkau dengan namamu, engkau kepunyaan-Ku."},
    {"ref": "Mazmur 121:5", "isi": "TUHANlah Penjagamu, TUHANlah naunganmu di sebelah tangan kananmu."},
    {"ref": "1 Yohanes 3:1", "isi": "Lihatlah, betapa besarnya kasih yang dikaruniakan Bapa kepada kita, sehingga kita disebut anak-anak Allah."},
    {"ref": "Roma 14:8", "isi": "Sebab jika kita hidup, kita hidup untuk Tuhan, dan jika kita mati, kita mati untuk Tuhan."},
    {"ref": "Amsal 18:24", "isi": "Ada teman yang mendatangkan kecelakaan, tetapi ada juga sahabat yang lebih karib dari pada seorang saudara."},
    {"ref": "Yohanes 15:9", "isi": "Seperti Bapa telah mengasihi Aku, demikianlah juga Aku telah mengasihi kamu; tinggallah di dalam kasih-Ku itu."},
    {"ref": "Mazmur 119:37", "isi": "Lalukanlah mataku dari pada melihat hal yang hampa, hidupkanlah aku dengan jalan-jalan yang Kauperintahkan!"},
    {"ref": "Filipi 4:9", "isi": "Dan Allah sumber damai sejahtera akan menyertai kamu."},
    {"ref": "1 Tesalonika 5:17", "isi": "Tetaplah berdoa."},
    {"ref": "Mazmur 5:13", "isi": "Sebab Engkaulah yang memberkati orang benar, ya TUHAN; Engkau memagari dia dengan kemurahan-Mu seperti perisai."},
    {"ref": "Ibrani 12:2", "isi": "Marilah kita melakukannya dengan mata yang tertuju kepada Yesus, yang memimpin kita dalam iman."},
    {"ref": "Amsal 21:23", "isi": "Siapa menjaga mulut dan lidahnya, memelihara diri dari pada kesukaran."},
    {"ref": "Matius 5:14", "isi": "Kamu adalah terang dunia. Kota yang terletak di atas gunung tidak mungkin tersembunyi."},
    {"ref": "Mazmur 119:71", "isi": "Bahwa aku tertindas itu baik bagiku, supaya aku belajar ketetapan-ketetapan-Mu."},
    {"ref": "Roma 8:18", "isi": "Sebab aku yakin, bahwa penderitaan zaman sekarang ini tidak dapat dibandingkan dengan kemuliaan yang akan dinyatakan."},
    {"ref": "Yakobus 1:12", "isi": "Berbahagialah orang yang bertahan dalam pencobaan, sebab apabila ia sudah tahan uji, ia akan menerima mahkota kehidupan."},
    {"ref": "Mazmur 145:14", "isi": "TUHAN itu penopang bagi semua orang yang jatuh dan penegak bagi semua orang yang tertunduk."},
    {"ref": "Yohanes 14:15", "isi": "Jikalau kamu mengasihi Aku, kamu akan menuruti segala perintah-Ku."},
    {"ref": "Amsal 11:25", "isi": "Siapa memberi berkat, diberi kelimpahan, siapa memberi minum, ia sendiri akan diberi minum."},
    {"ref": "2 Korintus 4:16", "isi": "Sebab itu kami tidak tawar hati, tetapi meskipun manusia lahiriah kami semakin merosot, namun manusia batiniah kami dibaharui."},
    {"ref": "Mazmur 34:19", "isi": "TUHAN itu dekat kepada orang-orang yang patah hati, dan Ia menyelamatkan orang-orang yang remuk jiwanya."},
    {"ref": "Matius 11:28", "isi": "Marilah kepada-Ku, semua yang letih lesu dan berbeban berat, Aku akan memberi kelegaan kepadamu."},
    {"ref": "1 Korintus 1:9", "isi": "Allah, yang memanggil kamu ke dalam persekutuan dengan Anak-Nya Yesus Kristus, Tuhan kita, adalah setia."},
    {"ref": "Mazmur 33:18", "isi": "Sesungguhnya, mata TUHAN tertuju kepada mereka yang takut akan Dia, kepada mereka yang berharap akan kasih setia-Nya."},
    {"ref": "Filipi 4:5", "isi": "Hendaklah kebaikan hatimu diketahui semua orang. Tuhan sudah dekat!"},
    {"ref": "Lukas 6:38", "isi": "Berilah dan kamu akan diberi: suatu takaran yang baik, yang dipadatkan, yang digoncang dan yang tumpah ke luar."},
    {"ref": "Amsal 15:33", "isi": "Takut akan TUHAN adalah didikan yang mendatangkan hikmat, dan kerendahan hati mendahului kehormatan."},
    {"ref": "Yohanes 10:27", "isi": "Domba-domba-Ku mendengarkan suara-Ku dan Aku mengenal mereka dan mereka mengikut Aku."},
    {"ref": "Mazmur 37:37", "isi": "Perhatikanlah orang yang tulus ikhlas dan lihatlah kepada orang yang jujur, sebab pada orang yang suka damai ada masa depan."},
    {"ref": "Ibrani 13:16", "isi": "Dan janganlah kamu lupa berbuat baik dan memberi bantuan, sebab korban-korban yang demikianlah yang berkenan kepada Allah."},
    {"ref": "Roma 12:10", "isi": "Hendaklah kamu saling mengasihi sebagai saudara dan saling mendahului dalam memberi hormat."},
    {"ref": "Amsal 16:32", "isi": "Orang yang sabar melebihi seorang pahlawan, orang yang menguasai dirinya, melebihi orang yang merebut kota."},
    {"ref": "Matius 6:21", "isi": "Karena di mana hartamu berada, di situ juga hatimu berada."},
    {"ref": "Mazmur 119:10", "isi": "Dengan segenap hatiku aku mencari Engkau, janganlah biarkan aku menyimpang dari perintah-perintah-Mu."},
    {"ref": "1 Petrus 3:11", "isi": "Ia harus menjauhi yang jahat dan melakukan yang baik, ia harus mencari perdamaian dan berusaha mendapatkannya."},
    {"ref": "Yohanes 11:25", "isi": "Jawab Yesus: Akulah kebangkitan dan hidup; barangsiapa percaya kepada-Ku, ia akan hidup walaupun ia sudah mati."},
    {"ref": "Mazmur 28:7", "isi": "TUHAN adalah kekuatanku dan perisaiku; kepada-Nya hatiku percaya. Aku tertolong sebab itu beria-ria hatiku."},
    {"ref": "Filipi 2:13", "isi": "Karena Allahlah yang mengerjakan di dalam kamu baik kemauan maupun pekerjaan menurut kerelaan-Nya."},
    {"ref": "Lukas 12:7", "isi": "Bahkan rambut kepalamupun terhitung semuanya. Karena itu jangan takut, karena kamu lebih berharga dari pada banyak burung pipit."},
    {"ref": "Amsal 12:25", "isi": "Kekuatiran dalam hati membungkukkan orang, tetapi perkataan yang baik menggembirakan dia."},
    {"ref": "Yohanes 15:11", "isi": "Semuanya ini Kukatakan kepadamu, supaya sukacita-Ku ada di dalam kamu dan sukacita-mu menjadi penuh."},
    {"ref": "Mazmur 118:1", "isi": "Bersyukurlah kepada TUHAN, sebab Ia baik! Bahwasanya untuk selama-lamanya kasih setia-Nya."},
    {"ref": "Efesus 3:20", "isi": "Bagi Dialah, yang dapat melakukan jauh lebih banyak dari pada yang kita doakan atau pikirkan."},
    {"ref": "Matius 5:13", "isi": "Kamu adalah garam dunia. Jika garam itu menjadi tawar, dengan apakah ia diasinkan?"},
    {"ref": "Mazmur 119:114", "isi": "Engkaulah persembunyianku dan perisaiku; aku berharap kepada firman-Mu."},
    {"ref": "1 Yohanes 4:7", "isi": "Saudara-saudaraku yang kekasih, marilah kita saling mengasihi, sebab kasih itu berasal dari Allah."},
    {"ref": "Roma 15:5", "isi": "Semoga Allah, yang adalah sumber ketekunan dan penghiburan, mengaruniakan kerukunan kepada kamu."},
    {"ref": "Amsal 10:12", "isi": "Kebencian menimbulkan pertengkaran, tetapi kasih menutupi segala pelanggaran."},
    {"ref": "Yohanes 13:17", "isi": "Jikalau kamu tahu semuanya ini, maka berbahagialah kamu, jika kamu melakukannya."},
    {"ref": "Mazmur 121:8", "isi": "TUHAN akan menjaga keluar masukmu, dari sekarang sampai selama-lamanya."},
    {"ref": "Filipi 4:12", "isi": "Aku tahu apa itu kekurangan dan aku tahu apa itu kelimpahan."},
    {"ref": "Matius 7:8", "isi": "Karena setiap orang yang meminta, menerima dan setiap orang yang mencari, mendapat dan setiap orang yang mengetok, baginya pintu dibukakan."},
    {"ref": "Mazmur 119:2", "isi": "Berbahagialah orang-orang yang memegang peringatan-peringatan-Nya, yang mencari Dia dengan segenap hati."},
    {"ref": "1 Tesalonika 5:11", "isi": "Karena itu nasihatilah seorang akan yang lain dan saling membangunlah kamu."},
    {"ref": "Yohanes 1:1", "isi": "Pada mulanya adalah Firman; Firman itu bersama-sama dengan Allah dan Firman itu adalah Allah."},
    {"ref": "Mazmur 147:5", "isi": "Besarlah Tuhan kita dan besarlah kekuatan-Nya, kebijaksanaan-Nya tidak terhingga."},
    {"ref": "Efesus 4:2", "isi": "Hendaklah kamu selalu rendah hati, lemah lembut, dan sabar. Tunjukkanlah kasihmu dalam hal saling membantu."},
    {"ref": "Amsal 11:2", "isi": "Jikalau keangkuhan tiba, tiba juga cemooh, tetapi hikmat ada pada orang yang rendah hati."},
    {"ref": "Yohanes 16:24", "isi": "Sampai sekarang kamu belum meminta sesuatupun dalam nama-Ku. Mintalah maka kamu akan menerima, supaya penuhlah sukacitamu."},
    {"ref": "Mazmur 32:8", "isi": "Aku hendak mengajar dan menunjukkan kepadamu jalan yang harus kautempuh; Aku hendak memberi nasihat, mata-Ku tertuju kepadamu."},
    {"ref": "Ibrani 13:1", "isi": "Peliharalah kasih persaudaraan!"},
    {"ref": "Roma 12:9", "isi": "Hendaklah kasih itu jangan pura-pura! Jauhilah yang jahat dan lakukanlah yang baik."},
    {"ref": "Amsal 15:23", "isi": "Seseorang bersukacita karena jawaban yang diberikannya, dan betapa baiknya perkataan yang tepat pada waktunya!"},
    {"ref": "Yohanes 5:24", "isi": "Aku berkata kepadamu: Sesungguhnya barangsiapa mendengar perkataan-Ku dan percaya kepada Dia yang mengutus Aku, ia mempunyai hidup yang kekal."},
    {"ref": "Mazmur 119:130", "isi": "Bila tersingkap, firman-firman-Mu memberi terang, memberi pengertian kepada orang-orang bodoh."},
    {"ref": "Filipi 1:21", "isi": "Karena bagiku hidup adalah Kristus dan mati adalah keuntungan."},
    {"ref": "Matius 6:14", "isi": "Karena jikalau kamu mengampuni kesalahan orang, Bapamu yang di sorga akan mengampuni kamu juga."},
    {"ref": "Mazmur 111:2", "isi": "Besar perbuatan-perbuatan TUHAN, layak diselidiki oleh semua orang yang menyukainya."},
    {"ref": "1 Petrus 1:24", "isi": "Sebab: Semua yang hidup adalah seperti rumput dan segala kemuliaannya seperti bunga rumput."},
    {"ref": "Roma 5:1", "isi": "Sebab itu, kita yang dibenarkan karena iman, kita hidup dalam damai sejahtera dengan Allah oleh karena Tuhan kita, Yesus Kristus."},
    {"ref": "Amsal 19:21", "isi": "Banyaklah rancangan di hati manusia, tetapi keputusan TUHANlah yang terlaksana."},
    {"ref": "Yohanes 12:26", "isi": "Barangsiapa melayani Aku, ia harus mengikut Aku dan di mana Aku berada, di situpun pelayan-Ku akan berada."},
    {"ref": "Mazmur 119:103", "isi": "Betapa manisnya janji-Mu itu bagi langit-langitku, lebih dari pada madu bagi mulutku."},
    {"ref": "Efesus 1:7", "isi": "Sebab di dalam Dia dan oleh darah-Nya kita beroleh penebusan, yaitu pengampunan dosa, menurut kekayaan kasih karunia-Nya."},
    {"ref": "Matius 5:5", "isi": "Berbahagialah orang yang lemah lembut, karena mereka akan memiliki bumi."},
    {"ref": "Mazmur 143:8", "isi": "Perdengarkanlah kasih setia-Mu kepadaku pada waktu pagi, sebab kepada-Mulah aku percaya!"},
    {"ref": "1 Yohanes 3:2", "isi": "Saudara-saudaraku yang kekasih, sekarang kita adalah anak-anak Allah."},
    {"ref": "Roma 10:9", "isi": "Sebab jika kamu mengaku dengan mulutmu, bahwa Yesus adalah Tuhan, dan percaya dalam hatimu, bahwa Allah telah membangkitkan Dia dari antara orang mati, maka kamu akan selamat."},
    {"ref": "Amsal 20:24", "isi": "Langkah manusia ditentukan oleh TUHAN, maka bagaimanakah manusia dapat mengerti jalannya sendiri?"},
    {"ref": "Yohanes 15:4", "isi": "Tinggallah di dalam Aku dan Aku di dalam kamu."},
    {"ref": "Mazmur 37:25", "isi": "Dahulu aku muda, sekarang telah menjadi tua, tetapi tidak pernah kulihat orang benar ditinggalkan."},
    {"ref": "Ibrani 10:23", "isi": "Marilah kita teguh berpegang pada pengakuan tentang pengharapan kita, sebab Ia, yang menjanjikannya, setia."},
    {"ref": "Lukas 12:24", "isi": "Perhatikanlah burung-burung gagak yang tidak menabur dan tidak menuai; namun mereka diberi makan oleh Allah."},
    {"ref": "Amsal 28:13", "isi": "Siapa menyembunyikan pelanggarannya tidak akan beruntung, tetapi siapa mengakuinya dan meninggalkannya akan disayang."},
    {"ref": "Yohanes 3:36", "isi": "Barangsiapa percaya kepada Anak, ia beroleh hidup yang kekal."},
    {"ref": "Mazmur 119:162", "isi": "Aku gembira atas janji-Mu, seperti orang yang mendapat jarahan banyak."},
    {"ref": "1 Yohanes 4:12", "isi": "Jikalau kita saling mengasihi, Allah tetap di dalam kita, dan kasih-Nya sempurna di dalam kita."},
    {"ref": "Roma 12:11", "isi": "Janganlah hendaknya kerajinanmu kendor, biarlah rohmu menyala-nyala dan layanilah Tuhan."},
    {"ref": "Amsal 24:16", "isi": "Sebab tujuh kali orang benar jatuh, namun ia bangun kembali."},
    {"ref": "Yohanes 10:9", "isi": "Akulah pintu; barangsiapa masuk melalui Aku, ia akan selamat."},
    {"ref": "Mazmur 145:13", "isi": "Kerajaan-Mu ialah kerajaan segala abad, dan pemerintahan-Mu tetap melalui segala keturunan."},
    {"ref": "Filipi 2:5", "isi": "Hendaklah kamu dalam hidupmu bersama, menaruh pikiran dan perasaan yang terdapat juga dalam Kristus Yesus."},
    {"ref": "Matius 25:40", "isi": "Sesungguhnya segala sesuatu yang kamu lakukan untuk salah seorang dari saudara-Ku yang paling hina ini, kamu telah melakukannya untuk Aku."},
    {"ref": "Mazmur 119:45", "isi": "Aku hendak hidup dalam kelegaan, sebab aku mencari titah-titah-Mu."},
    {"ref": "1 Tesalonika 5:24", "isi": "Ia yang memanggil kamu adalah setia, Ia juga akan menggenapinya."},
    {"ref": "Yohanes 7:38", "isi": "Barangsiapa percaya kepada-Ku, seperti yang dikatakan oleh Kitab Suci: Dari dalam hatinya akan mengalir aliran-aliran air hidup."},
    {"ref": "Mazmur 119:77", "isi": "Biarlah rahmat-Mu sampai kepadaku, supaya aku hidup, sebab Taurat-Mu adalah kegirangan hatiku."},
    {"ref": "Roma 11:36", "isi": "Sebab segala sesuatu adalah dari Dia, dan oleh Dia, dan kepada Dia: Bagi Dialah kemuliaan sampai selama-lamanya!"},
    {"ref": "Amsal 30:5", "isi": "Semua firman Allah adalah murni. Ia adalah perisai bagi orang-orang yang berlindung pada-Nya."},
  ];

  static Map<String, String> getAyatAcak() {
    final random = Random();
    return daftarAyat[random.nextInt(daftarAyat.length)];
  }
}