name: Flutter Build APK

# Perubahan di sini agar tidak otomatis setiap push
on: 
  workflow_dispatch: # Ini akan memunculkan tombol "Run Workflow" di GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Decode Keystore
        run: echo "${{ secrets.APP_KEYSTORE_BASE64 }}" | base64 --decode > android/app/gereja-app.jks

      - name: Get Dependencies
        run: flutter pub get
        working-directory: . 

      - name: Build APK
        # Menggunakan build release agar APK lebih ringan dan resmi
        run: flutter build apk --release
        working-directory: .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk