name: Flutter Build APK

on: 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 1. Cache Gradle untuk mempercepat kompilasi Android
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 2. Setup Flutter dengan cache SDK bawaan
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true 

      - name: Decode Keystore
        run: echo "${{ secrets.APP_KEYSTORE_BASE64 }}" | base64 --decode > android/app/gereja-app.jks

      # JURUS SAPU JAGAT: Bersihkan memori mesin GitHub sampai ke akar
      - name: Bersihkan Ingatan Server
        run: |
          flutter clean
          flutter pub cache clean -f

      - name: Get Dependencies
        run: flutter pub get
        working-directory: . 

      # 👇 INI DIA MANTRA BARU KITA BOS: EKSEKUSI IKON & SPLASH SCREEN 👇
      - name: Generate Icon & Splash Screen
        run: |
          dart run flutter_launcher_icons
        working-directory: . 

# JURUS SAKTI PENYUNTIK BRANKAS LENGKAP
      - name: Create Secrets File
        run: |
          mkdir -p lib
          echo "const String geminiApiKey = '${{ secrets.GEMINI_API_KEY }}';" > lib/secrets.dart
          echo "const String teleBotTokenSecret = '${{ secrets.TELE_BOT_TOKEN }}';" >> lib/secrets.dart
          echo "const String osRestKeySecret = '${{ secrets.ONESIGNAL_REST_KEY }}';" >> lib/secrets.dart
          echo "const String pixabayApiKey = '${{ secrets.PIXABAY_API_KEY }}';" >> lib/secrets.dart
      
      - name: Build APK
        run: flutter build apk --release
        working-directory: .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk